GeekseatWitchSaga/GeekseatWitchSaga/Models/ErrorViewModel.cs
using System;

namespace GeekseatWitchSaga.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GeekseatWitchSaga/GeekseatWitchSaga/Models/VillagerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GeekseatWitchSaga.Models
{
    public class VillagerData
    {
        public int ID { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Only positive number allowed.")]
        [Display(Name = "Age of Death")]
        public int iAge { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Only positive number allowed.")]
        [Display(Name = "Year of Death")]
        public int iYear { get; set; }
    }

    public interface IVillager
    {
        decimal GetAverageNumberOfKilledVillager();
    }
}

GeekseatWitchSaga/GeekseatWitchSaga/Controllers/HomeController.cs
using GeekseatWitchSaga.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GeekseatWitchSaga.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GeekseatWitchSaga/GeekseatWitchSaga/Controllers/VillagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GeekseatWitchSaga.Data;
using GeekseatWitchSaga.Models;

namespace GeekseatWitchSaga.Controllers
{
    public class VillagerController : Controller, IVillager
    {
        private readonly GeekseatWitchSagaContext _context;

        public VillagerController(GeekseatWitchSagaContext context)
        {
            _context = context;
        }

        // GET: Villager
        public async Task<IActionResult> Index()
        {
            ViewData["AverageNumber"] = GetAverageNumberOfKilledVillager();
            return View(await _context.VillagerData.ToListAsync());
        }

        // GET: Villager/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var villagerData = await _context.VillagerData
                .FirstOrDefaultAsync(m => m.ID == id);
            if (villagerData == null)
            {
                return NotFound();
            }

            return View(villagerData);
        }

        // GET: Villager/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Villager/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,iAge,iYear")] VillagerData villagerData)
        {
            if (ModelState.IsValid)
            {
                _context.Add(villagerData);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(villagerData);
        }

        // GET: Villager/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var villagerData = await _context.VillagerData.FindAsync(id);
            if (villagerData == null)
            {
                return NotFound();
            }
            return View(villagerData);
        }

        // POST: Villager/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,iAge,iYear")] VillagerData villagerData)
        {
            if (id != villagerData.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(villagerData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VillagerDataExists(villagerData.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(villagerData);
        }

        // GET: Villager/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var villagerData = await _context.VillagerData
                .FirstOrDefaultAsync(m => m.ID == id);
            if (villagerData == null)
            {
                return NotFound();
            }

            return View(villagerData);
        }

        // POST: Villager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var villagerData = await _context.VillagerData.FindAsync(id);
            _context.VillagerData.Remove(villagerData);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VillagerDataExists(int id)
        {
            return _context.VillagerData.Any(e => e.ID == id);
        }

        public decimal GetAverageNumberOfKilledVillager()
        {
            long totalKilled = 0;
            long counter = 0;
            foreach(var villagerData in _context.VillagerData)
            {
                int iBornOnYear = villagerData.iYear - villagerData.iAge;
                if (iBornOnYear < 0)
                    return -1m;

                totalKilled += GetNumberOfKilledVillagerInYear(iBornOnYear);
                counter++;
            }
            if (counter == 0)
                return -1m;
            else
                return (decimal)totalKilled/counter;
        }

        Dictionary<int, long> _memoryOfKilledVillager = new Dictionary<int, long>();
        public long GetNumberOfKilledVillagerInYear(int iBornOnYear)
        {
            if (_memoryOfKilledVillager.ContainsKey(iBornOnYear))
                return _memoryOfWitchRule[iBornOnYear];

            var value = WitchRules(iBornOnYear + 2) - 1;
            _memoryOfKilledVillager[iBornOnYear] = value;

            return value;
        }

        Dictionary<int, long> _memoryOfWitchRule = new Dictionary<int, long>() { { 0, 0 }, { 1, 1 } };
        public long WitchRules(int n)
        {
            if (n < 0)
                return 0;

            if (_memoryOfWitchRule.ContainsKey(n))
                return _memoryOfWitchRule[n];

            var value = WitchRules(n - 1) + WitchRules(n - 2);

            _memoryOfWitchRule[n] = value;

            return value;
        }
    }
}

GeekseatWitchSaga/GeekseatWitchSaga/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GeekseatWitchSaga/GeekseatWitchSaga/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeekseatWitchSaga</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Villager" asp-action="Index">GeekseatWitchSaga</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villager" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GeekseatWitchSaga - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GeekseatWitchSaga/GeekseatWitchSaga/Views/Villager/Create.cshtml
@model GeekseatWitchSaga.Models.VillagerData

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Villager Data</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="iAge" class="control-label"></label>
                <input asp-for="iAge" class="form-control" />
                <span asp-validation-for="iAge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="iYear" class="control-label"></label>
                <input asp-for="iYear" class="form-control" />
                <span asp-validation-for="iYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GeekseatWitchSaga/GeekseatWitchSaga/Views/Villager/Delete.cshtml
@model GeekseatWitchSaga.Models.VillagerData

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Villager Data</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.iAge)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.iAge)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.iYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.iYear)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GeekseatWitchSaga/GeekseatWitchSaga/Views/Villager/Details.cshtml
@model GeekseatWitchSaga.Models.VillagerData

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Villager Data</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.iAge)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.iAge)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.iYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.iYear)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GeekseatWitchSaga/GeekseatWitchSaga/Views/Villager/Edit.cshtml
@model GeekseatWitchSaga.Models.VillagerData

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Villager Data</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="iAge" class="control-label"></label>
                <input asp-for="iAge" class="form-control" />
                <span asp-validation-for="iAge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="iYear" class="control-label"></label>
                <input asp-for="iYear" class="form-control" />
                <span asp-validation-for="iYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GeekseatWitchSaga/GeekseatWitchSaga/Views/Villager/Index.cshtml
@model IEnumerable<GeekseatWitchSaga.Models.VillagerData>

@{
    ViewData["Title"] = "Index";
}

<h1>Vilager Data</h1>
<h2>
    Average number of villager that killed by the witch : @Convert.ToDecimal(ViewData["AverageNumber"]).ToString("0.##")
</h2>


<br />

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.iAge)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.iYear)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.iAge)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.iYear)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>